#!/usr/bin/env python3
from __future__ import annotations

import json
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
REPORTS_DIR = ROOT / "outputs" / "reports"

PROTECTED_PATHS = [
    "outputs/final_submission",
    "outputs/eval_results_strict.json",
    "outputs/hidden_style_eval.md",
    "outputs/hidden_style_eval.json",
    "outputs/winner_readiness_report.json",
    "outputs/final_submission_manifest.json",
    "final_submission_manifest.json",
    ".env.local",
    "pyproject.toml",
    "scripts/package_submission.py",
    "scripts/package_query_outputs.py",
    "scripts/check_submission_ready.py",
    "dashagent",
    "dashagent/endpoint_catalog.py",
]

SAFE_FIRST_BATCH = {
    ".pytest_cache": "local pytest cache; regenerated by pytest and not packaged",
    ".playwright-cli": "temporary Playwright CLI smoke-test state; not required by repo validation",
    "outputs/core_tool_correctness_trials": "small per-variant correctness trial outputs; final md/json reports are preserved",
    "outputs/sdk_tool_calling_optimization_trials": "small SDK tool-calling trial outputs; final md/json reports are preserved",
    "outputs/type_specific_deterministic_rule_trials": "small type-specific trial outputs; final md/json reports are preserved",
}

OUTPUT_CANDIDATES = {
    "outputs/generated_prompt_suite_local_diagnostic": {
        "report_stem": "generated_prompt_suite_local_diagnostic",
        "reason": "large per-prompt local diagnostic artifacts; final local diagnostic report is preserved",
    },
    "outputs/generated_prompt_suite_diagnostic": {
        "report_stem": "full_generated_prompt_suite_diagnostic",
        "reason": "full generated prompt diagnostic artifacts; final report is preserved",
    },
    "outputs/diagnostic_prompt_suite": {
        "report_stem": "diagnostic_prompt_suite_run",
        "reason": "generated prompt runtime artifacts; final report is preserved",
    },
    "outputs/sdk_tool_calling_optimization_trials": {
        "report_stem": "sdk_tool_calling_optimization_trials",
        "reason": SAFE_FIRST_BATCH["outputs/sdk_tool_calling_optimization_trials"],
    },
    "outputs/score_focused_core_improvement_trials": {
        "report_stem": "score_focused_core_improvement_trials",
        "reason": "score-focused answer trial artifacts; final report and fix decision are preserved",
    },
    "outputs/evidence_aware_answer_rewrite_trial": {
        "report_stem": "evidence_aware_answer_rewrite_trial",
        "reason": "answer-rewrite trial artifacts; final report is preserved",
    },
    "outputs/type_specific_deterministic_rule_trials": {
        "report_stem": "type_specific_deterministic_rule_trials",
        "reason": SAFE_FIRST_BATCH["outputs/type_specific_deterministic_rule_trials"],
    },
    "outputs/core_tool_correctness_trials": {
        "report_stem": "core_tool_correctness_trials",
        "reason": SAFE_FIRST_BATCH["outputs/core_tool_correctness_trials"],
    },
    "outputs/live_api_evidence_pipeline_trial": {
        "report_stem": "live_api_evidence_pipeline_trial",
        "reason": "safe live-pipeline trial artifacts; final report is preserved",
    },
    "outputs/mock_live_api_evidence_pipeline_trial": {
        "report_stem": "mock_live_api_evidence_pipeline_trial",
        "reason": "mock live-pipeline trial artifacts; final report is preserved",
    },
    "outputs/llm_semantic_router_isolated_trial": {
        "report_stem": "llm_semantic_router_isolated_trial",
        "reason": "semantic-router isolated trial artifacts; final report is preserved",
    },
    "outputs/autonomous_packaged_trial": {
        "report_stem": "../autonomous_packaged_trial",
        "reason": "legacy autonomous packaged trial artifacts; final top-level report is preserved",
    },
    "outputs/official_token_reduction_packaged_trial": {
        "report_stem": "../official_token_reduction_packaged_trial",
        "reason": "legacy official-token trial artifacts; final top-level report is preserved",
    },
}

CACHE_CANDIDATES = {
    ".pytest_cache": SAFE_FIRST_BATCH[".pytest_cache"],
    ".playwright-cli": SAFE_FIRST_BATCH[".playwright-cli"],
    "dashagent/__pycache__": "Python bytecode cache; regenerated automatically",
    "scripts/__pycache__": "Python bytecode cache; regenerated automatically",
    "tests/__pycache__": "Python bytecode cache; regenerated automatically",
    "node_modules": "local Node dependency folder from browser tooling; not part of Python validation or submission",
}


def main() -> int:
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    payload = audit_repo_cleanup_candidates()
    print(
        json.dumps(
            {
                "inventory": "outputs/reports/repo_cleanup_candidate_inventory.json",
                "deletion_plan": "outputs/reports/repo_cleanup_deletion_plan.json",
                "delete_path_count": len(payload["deletion_plan"]["paths_proposed_for_deletion"]),
                "manual_review_count": len(payload["manual_review"]),
                "blocker": payload["preflight"]["blocker"],
            },
            indent=2,
            sort_keys=True,
        )
    )
    return 0 if not payload["preflight"]["blocker"] else 2


def audit_repo_cleanup_candidates() -> dict[str, Any]:
    generated_at = _now()
    status_lines = _git_status()
    tracked = set(_git_lines(["git", "ls-files"]))
    references = _collect_references()
    linked_reports = _linked_reports(references)

    system = _load_json(REPORTS_DIR / "system_summary.json")
    strict = _load_json(ROOT / "outputs" / "eval_results_strict.json")
    hidden = _load_json(ROOT / "outputs" / "hidden_style_eval.json")
    readiness = _submission_readiness_summary()

    preflight = {
        "report_type": "repo_cleanup_preflight",
        "generated_at": generated_at,
        "git_status": status_lines,
        "git_status_summary": _status_summary(status_lines),
        "protected_artifacts_found": _protected_artifacts_found(),
        "current_packaged_strategy": system.get("preferred_strategy") or "SQL_FIRST_API_VERIFY",
        "strict_score": _strict_score(strict, system),
        "hidden_style": (system.get("hidden_style") or {}).get("label") or _hidden_label(hidden),
        "final_submission_ready": readiness.get("ok", system.get("final_submission_ready")),
        "cleanup_mode": "safe deletion only",
        "runtime_changes_allowed": False,
        "final_submission_writes_allowed": False,
        "protected_deletions": _protected_dirty(status_lines, deletion_only=True),
        "dirty_runtime_sources": _dirty_runtime_sources(status_lines),
    }
    preflight["blocker"] = bool(preflight["protected_deletions"] or preflight["dirty_runtime_sources"])
    _write_pair("repo_cleanup_preflight", preflight, _render_preflight(preflight))
    if preflight["blocker"]:
        blocker = {
            "report_type": "repo_cleanup_blocker",
            "generated_at": generated_at,
            "reason": "Protected deletion or runtime-source dirty state detected before cleanup.",
            "protected_deletions": preflight["protected_deletions"],
            "dirty_runtime_sources": preflight["dirty_runtime_sources"],
            "runtime_changes_allowed": False,
        }
        _write_pair("repo_cleanup_blocker", blocker, _render_blocker(blocker))

    inventory = _build_inventory(generated_at, references, linked_reports, tracked)
    _write_pair("repo_cleanup_candidate_inventory", inventory, _render_inventory(inventory))
    plan = _build_deletion_plan(generated_at, inventory)
    _write_pair("repo_cleanup_deletion_plan", plan, _render_plan(plan))

    return {
        "preflight": preflight,
        "inventory": inventory,
        "deletion_plan": plan,
        "manual_review": inventory["by_recommended_action"].get("manual_review", []),
    }


def _build_inventory(
    generated_at: str,
    references: dict[str, list[str]],
    linked_reports: set[str],
    tracked: set[str],
) -> dict[str, Any]:
    items: list[dict[str, Any]] = []

    for path in PROTECTED_PATHS:
        p = ROOT / path
        if p.exists():
            items.append(
                {
                    **_path_info(path, tracked),
                    "category": "keep_required_runtime",
                    "reason": "protected artifact or packaged runtime dependency",
                    "referenced_by": references.get(path, []),
                    "final_report_kept": None,
                    "deletion_risk": "high",
                    "recommended_action": "keep",
                }
            )

    for path in sorted(linked_reports):
        p = ROOT / path
        if p.exists():
            items.append(
                {
                    **_path_info(path, tracked),
                    "category": "keep_required_report",
                    "reason": "linked from report_index/system_summary or consolidated report surface",
                    "referenced_by": references.get(path, []),
                    "final_report_kept": path,
                    "deletion_risk": "high",
                    "recommended_action": "keep",
                }
            )

    for path in sorted(_validation_scripts_from_docs(references)):
        p = ROOT / path
        if p.exists():
            items.append(
                {
                    **_path_info(path, tracked),
                    "category": "keep_required_validation",
                    "reason": "referenced by README/AGENTS/Skill/report validation command matrix",
                    "referenced_by": references.get(path, []),
                    "final_report_kept": None,
                    "deletion_risk": "high",
                    "recommended_action": "keep",
                }
            )

    for path, reason in CACHE_CANDIDATES.items():
        if not (ROOT / path).exists():
            continue
        info = _path_info(path, tracked)
        action = "delete" if path in SAFE_FIRST_BATCH else "manual_review"
        risk = "low" if action == "delete" else "medium"
        items.append(
            {
                **info,
                "category": "delete_candidate_intermediate_output" if action == "delete" else "keep_manual_review",
                "reason": reason,
                "referenced_by": references.get(path, []),
                "final_report_kept": None,
                "deletion_risk": risk,
                "recommended_action": action,
            }
        )

    for path, meta in OUTPUT_CANDIDATES.items():
        if not (ROOT / path).exists():
            continue
        report_paths = _report_pair_for_stem(meta["report_stem"])
        reports_exist = all((ROOT / report).exists() for report in report_paths)
        info = _path_info(path, tracked)
        action = "delete" if path in SAFE_FIRST_BATCH and reports_exist and info["file_count"] <= 10 else "manual_review"
        risk = "low" if action == "delete" else "medium"
        items.append(
            {
                **info,
                "category": "delete_candidate_intermediate_output" if action == "delete" else "keep_manual_review",
                "reason": meta["reason"],
                "referenced_by": references.get(path, []),
                "final_report_kept": list(report_paths) if reports_exist else None,
                "deletion_risk": risk,
                "recommended_action": action if reports_exist else "manual_review",
            }
        )

    items = _dedupe_items(items)
    by_action: dict[str, list[str]] = {}
    by_category: dict[str, int] = {}
    for item in items:
        by_action.setdefault(item["recommended_action"], []).append(item["path"])
        by_category[item["category"]] = by_category.get(item["category"], 0) + 1

    return {
        "report_type": "repo_cleanup_candidate_inventory",
        "generated_at": generated_at,
        "diagnostic_only": True,
        "runtime_behavior_changed": False,
        "classification_rules": [
            "Protected artifacts, linked final reports, validation scripts, packaged runtime code, and final submission artifacts are kept.",
            "Unpromoted diagnostic/trial output directories are delete candidates only when final md/json reports exist.",
            "Large or heavily referenced candidates are left for manual review.",
            "The first deletion batch must stay under 50 files and 50 MB.",
        ],
        "items": items,
        "by_recommended_action": by_action,
        "by_category_count": by_category,
        "total_size_bytes": sum(int(item.get("size_bytes") or 0) for item in items),
    }


def _build_deletion_plan(generated_at: str, inventory: dict[str, Any]) -> dict[str, Any]:
    delete_items = [item for item in inventory["items"] if item["recommended_action"] == "delete"]
    previous_result = _load_json(REPORTS_DIR / "repo_cleanup_result.json")
    total_files = sum(int(item.get("file_count") or 0) for item in delete_items)
    total_size = sum(int(item.get("size_bytes") or 0) for item in delete_items)
    batch_note = "safe first batch"
    if total_files > 50 or total_size > 50 * 1024 * 1024:
        kept: list[dict[str, Any]] = []
        files = 0
        size = 0
        for item in delete_items:
            next_files = files + int(item.get("file_count") or 0)
            next_size = size + int(item.get("size_bytes") or 0)
            if next_files <= 50 and next_size <= 50 * 1024 * 1024:
                kept.append(item)
                files = next_files
                size = next_size
        delete_items = kept
        total_files = files
        total_size = size
        batch_note = "split first batch because the full candidate set exceeded safety threshold"

    return {
        "report_type": "repo_cleanup_deletion_plan",
        "generated_at": generated_at,
        "cleanup_mode": "safe deletion only",
        "batch_note": batch_note,
        "paths_proposed_for_deletion": [
            {
                "path": item["path"],
                "reason": item["reason"],
                "size_bytes": item["size_bytes"],
                "file_count": item["file_count"],
                "tracked_file_count": item["tracked_file_count"],
                "final_report_kept": item.get("final_report_kept"),
                "risk_level": item["deletion_risk"],
            }
            for item in delete_items
        ],
        "expected_size_reduction_bytes": total_size,
        "expected_file_reduction_count": total_files,
        "references_removed_or_updated": [],
        "manual_review_paths": inventory["by_recommended_action"].get("manual_review", []),
        "previous_cleanup_result_paths_deleted": previous_result.get("paths_deleted", []),
        "previous_cleanup_result_status": previous_result.get("status"),
        "rollback_note": "Restore deleted tracked files with git restore -- <path>; untracked caches can be regenerated by validation commands.",
        "protected_paths_not_deleted": PROTECTED_PATHS,
    }


def _path_info(path: str, tracked: set[str]) -> dict[str, Any]:
    p = ROOT / path
    if p.is_file():
        file_count = 1
        size = p.stat().st_size
    elif p.is_dir():
        files = [child for child in p.rglob("*") if child.is_file()]
        file_count = len(files)
        size = sum(child.stat().st_size for child in files)
    else:
        file_count = 0
        size = 0
    prefix = path.rstrip("/") + "/"
    tracked_count = sum(1 for item in tracked if item == path or item.startswith(prefix))
    return {
        "path": path,
        "exists": p.exists(),
        "size_bytes": size,
        "file_count": file_count,
        "tracked_file_count": tracked_count,
    }


def _collect_references() -> dict[str, list[str]]:
    docs = [
        "README.md",
        "AGENTS.md",
        "skills/dashsys_project_skill/SKILL.md",
        "skills/dashsys_project_skill/checklists.md",
        "outputs/reports/system_summary.md",
        "outputs/reports/report_index.md",
    ]
    refs: dict[str, set[str]] = {}
    pattern = re.compile(r"(?:outputs|scripts|dashagent|tests|skills)/[A-Za-z0-9_./-]+")
    for doc in docs:
        p = ROOT / doc
        if not p.exists():
            continue
        text = p.read_text(encoding="utf-8", errors="ignore")
        for match in pattern.findall(text):
            normalized = match.rstrip("`.,)")
            refs.setdefault(normalized, set()).add(doc)
    for json_path in [REPORTS_DIR / "report_index.json", REPORTS_DIR / "system_summary.json"]:
        data = _load_json(json_path)
        for value in _walk_strings(data):
            if value.startswith(("outputs/", "scripts/", "dashagent/", "tests/", "skills/")):
                refs.setdefault(value.rstrip("`.,)"), set()).add(str(json_path.relative_to(ROOT)))
    return {key: sorted(value) for key, value in refs.items()}


def _linked_reports(references: dict[str, list[str]]) -> set[str]:
    reports = {path for path in references if path.startswith("outputs/reports/")}
    reports.update(path for path in references if path.startswith("outputs/visualizations/"))
    reports.update(
        {
            "outputs/eval_results_strict.json",
            "outputs/winner_readiness_report.json",
            "outputs/hidden_style_eval.md",
            "outputs/hidden_style_eval.json",
            "outputs/final_submission_manifest.json",
        }
    )
    return reports


def _validation_scripts_from_docs(references: dict[str, list[str]]) -> set[str]:
    return {path for path in references if path.startswith("scripts/") and path.endswith(".py")}


def _report_pair_for_stem(stem: str) -> tuple[str, str]:
    if stem.startswith("../"):
        base = "outputs/" + stem[3:]
        return f"{base}.md", f"{base}.json"
    return f"outputs/reports/{stem}.md", f"outputs/reports/{stem}.json"


def _dedupe_items(items: list[dict[str, Any]]) -> list[dict[str, Any]]:
    seen: dict[str, dict[str, Any]] = {}
    priority = {"keep": 4, "manual_review": 3, "delete": 2}
    for item in items:
        old = seen.get(item["path"])
        if old is None or priority.get(item["recommended_action"], 0) > priority.get(old["recommended_action"], 0):
            seen[item["path"]] = item
    return sorted(seen.values(), key=lambda item: (item["recommended_action"], item["category"], item["path"]))


def _protected_artifacts_found() -> list[str]:
    return [path for path in PROTECTED_PATHS if (ROOT / path).exists()]


def _protected_dirty(status_lines: list[str], deletion_only: bool) -> list[str]:
    out: list[str] = []
    for line in status_lines:
        if not line:
            continue
        code = line[:2]
        path = line[3:].strip()
        if " -> " in path:
            path = path.split(" -> ", 1)[-1]
        if deletion_only and "D" not in code:
            continue
        if _is_protected(path):
            out.append(line)
    return out


def _dirty_runtime_sources(status_lines: list[str]) -> list[str]:
    out: list[str] = []
    for line in status_lines:
        path = line[3:].strip() if len(line) > 3 else ""
        if " -> " in path:
            path = path.split(" -> ", 1)[-1]
        if path.startswith("dashagent/"):
            out.append(line)
    return out


def _is_protected(path: str) -> bool:
    clean = path.rstrip("/")
    for protected in PROTECTED_PATHS:
        protected = protected.rstrip("/")
        if clean == protected or clean.startswith(protected + "/"):
            return True
    return False


def _status_summary(status_lines: list[str]) -> dict[str, Any]:
    return {
        "line_count": len(status_lines),
        "modified_count": sum(1 for line in status_lines if line[:2].strip() == "M"),
        "deleted_count": sum(1 for line in status_lines if "D" in line[:2]),
        "untracked_count": sum(1 for line in status_lines if line.startswith("??")),
    }


def _submission_readiness_summary() -> dict[str, Any]:
    manifest = ROOT / "outputs" / "final_submission_manifest.json"
    final_dir = ROOT / "outputs" / "final_submission"
    return {
        "ok": manifest.exists() and final_dir.exists(),
        "manifest_exists": manifest.exists(),
        "final_submission_dir_exists": final_dir.exists(),
    }


def _strict_score(strict: dict[str, Any], system: dict[str, Any]) -> Any:
    by_strategy = ((strict.get("summary") or {}).get("by_strategy") or {}).get("SQL_FIRST_API_VERIFY") or {}
    return system.get("packaged_strict_score") or by_strategy.get("avg_final_score")


def _hidden_label(hidden: dict[str, Any]) -> str:
    summary = hidden.get("summary") or {}
    passed = summary.get("passed_cases")
    total = summary.get("total_cases")
    if passed is not None and total is not None:
        return f"{passed}/{total}"
    return "unknown"


def _git_status() -> list[str]:
    return _git_lines(["git", "status", "--short"])


def _git_lines(command: list[str]) -> list[str]:
    try:
        result = subprocess.run(command, cwd=ROOT, text=True, capture_output=True, check=False, timeout=10)
    except Exception:
        return []
    return [line for line in result.stdout.splitlines() if line.strip()]


def _load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _walk_strings(value: Any) -> list[str]:
    if isinstance(value, str):
        return [value]
    if isinstance(value, list):
        out: list[str] = []
        for item in value:
            out.extend(_walk_strings(item))
        return out
    if isinstance(value, dict):
        out = []
        for item in value.values():
            out.extend(_walk_strings(item))
        return out
    return []


def _write_pair(stem: str, payload: dict[str, Any], markdown: str) -> None:
    safe = _redact(payload)
    (REPORTS_DIR / f"{stem}.json").write_text(json.dumps(safe, indent=2, sort_keys=True), encoding="utf-8")
    (REPORTS_DIR / f"{stem}.md").write_text(markdown, encoding="utf-8")


def _redact(value: Any) -> Any:
    if isinstance(value, str):
        value = re.sub(r"Authorization:\s*Bearer\s+\S+", "Authorization: <redacted>", value, flags=re.I)
        value = re.sub(r"Bearer\s+[A-Za-z0-9._-]+", "Bearer <redacted>", value, flags=re.I)
        value = re.sub(r"\b[A-Za-z0-9]{3}\*\*\*", "<redacted-prefix>", value)
        return value
    if isinstance(value, list):
        return [_redact(item) for item in value]
    if isinstance(value, dict):
        return {key: _redact(item) for key, item in value.items()}
    return value


def _render_preflight(payload: dict[str, Any]) -> str:
    return "\n".join(
        [
            "# Repo Cleanup Preflight",
            "",
            f"- Generated at: `{payload['generated_at']}`",
            f"- Packaged strategy: `{payload['current_packaged_strategy']}`",
            f"- Strict score: `{payload['strict_score']}`",
            f"- Hidden-style: `{payload['hidden_style']}`",
            f"- Final submission ready: `{payload['final_submission_ready']}`",
            f"- Cleanup mode: `{payload['cleanup_mode']}`",
            f"- Runtime changes allowed: `{payload['runtime_changes_allowed']}`",
            f"- Final-submission writes allowed: `{payload['final_submission_writes_allowed']}`",
            f"- Blocker: `{payload['blocker']}`",
            "",
            "## Protected Artifacts Found",
            "",
            *[f"- `{path}`" for path in payload["protected_artifacts_found"]],
            "",
            "## Git Status Summary",
            "",
            *[f"- {key}: `{value}`" for key, value in payload["git_status_summary"].items()],
        ]
    ) + "\n"


def _render_blocker(payload: dict[str, Any]) -> str:
    return "\n".join(
        [
            "# Repo Cleanup Blocker",
            "",
            payload["reason"],
            "",
            "## Protected Deletions",
            "",
            *[f"- `{line}`" for line in payload["protected_deletions"]],
            "",
            "## Dirty Runtime Sources",
            "",
            *[f"- `{line}`" for line in payload["dirty_runtime_sources"]],
        ]
    ) + "\n"


def _render_inventory(payload: dict[str, Any]) -> str:
    lines = [
        "# Repo Cleanup Candidate Inventory",
        "",
        f"- Generated at: `{payload['generated_at']}`",
        f"- Runtime behavior changed: `{payload['runtime_behavior_changed']}`",
        "",
        "## Classification Rules",
        "",
    ]
    lines.extend(f"- {rule}" for rule in payload["classification_rules"])
    lines.extend(["", "## Recommended Actions", ""])
    for action, paths in sorted(payload["by_recommended_action"].items()):
        lines.append(f"- `{action}`: `{len(paths)}` paths")
    lines.extend(["", "## Delete Candidates", ""])
    for item in payload["items"]:
        if item["recommended_action"] == "delete":
            lines.append(
                f"- `{item['path']}` - {item['reason']} "
                f"({item['file_count']} files, {item['size_bytes']} bytes)"
            )
    lines.extend(["", "## Manual Review", ""])
    for path in payload["by_recommended_action"].get("manual_review", []):
        lines.append(f"- `{path}`")
    return "\n".join(lines) + "\n"


def _render_plan(payload: dict[str, Any]) -> str:
    lines = [
        "# Repo Cleanup Deletion Plan",
        "",
        f"- Generated at: `{payload['generated_at']}`",
        f"- Cleanup mode: `{payload['cleanup_mode']}`",
        f"- Batch note: `{payload['batch_note']}`",
        f"- Expected size reduction: `{payload['expected_size_reduction_bytes']}` bytes",
        f"- Expected file reduction: `{payload['expected_file_reduction_count']}` files",
        "",
        "## Paths Proposed For Deletion",
        "",
    ]
    for item in payload["paths_proposed_for_deletion"]:
        lines.append(
            f"- `{item['path']}` - {item['reason']} "
            f"(risk `{item['risk_level']}`, final report `{item['final_report_kept']}`)"
        )
    lines.extend(["", "## Manual Review Paths", ""])
    for path in payload["manual_review_paths"]:
        lines.append(f"- `{path}`")
    lines.extend(["", "## Previous Cleanup Result Paths Deleted", ""])
    for path in payload.get("previous_cleanup_result_paths_deleted", []):
        lines.append(f"- `{path}`")
    lines.extend(["", "## Rollback", "", payload["rollback_note"]])
    return "\n".join(lines) + "\n"


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")


if __name__ == "__main__":
    raise SystemExit(main())
