#!/usr/bin/env python
from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from visualization_report_helpers import (  # noqa: E402
    UNAVAILABLE,
    VIS_DIR,
    get_path,
    load_json,
    md_escape,
    score_delta,
    source,
    strict_strategy_summary,
    table,
    write_json,
    write_md,
)


EFFECT_KEYS = [
    "strict_score_delta",
    "correctness_delta",
    "answer_score_delta",
    "sql_score_delta",
    "api_score_delta",
    "token_delta",
    "runtime_delta",
    "tool_call_delta",
]


def empty_effect() -> dict[str, Any]:
    return {key: UNAVAILABLE for key in EFFECT_KEYS}


def main() -> int:
    catalog = build_catalog()
    write_json(VIS_DIR / "technique_catalog.json", {"techniques": catalog, "total": len(catalog)})
    write_md(VIS_DIR / "technique_catalog.md", build_markdown(catalog))
    print({"json": str(VIS_DIR / "technique_catalog.json"), "markdown": str(VIS_DIR / "technique_catalog.md"), "total": len(catalog)})
    return 0


def build_catalog() -> list[dict[str, Any]]:
    reports = load_reports()
    current = strict_strategy_summary()

    def technique(
        name: str,
        category: str,
        purpose: str,
        stage: str,
        input_data: str,
        output_data: str,
        decision_boundary: str,
        files: list[str],
        checkpoints: list[str],
        default_state: str,
        effect: dict[str, Any] | None,
        hidden_style_impact: Any,
        rationale: str,
        sources: list[dict[str, str]],
    ) -> dict[str, Any]:
        payload = {
            "technique_name": name,
            "category": category,
            "purpose": purpose,
            "stage_in_pipeline": stage,
            "input_data": input_data,
            "output_data": output_data,
            "decision_boundary": decision_boundary,
            "files_modules_involved": files,
            "checkpoint_names_involved": checkpoints,
            "default_state": default_state,
            "measured_effect": effect or empty_effect(),
            "hidden_style_impact": hidden_style_impact,
            "safety_notes": decision_boundary,
            "why_promoted_or_not": rationale,
            "source_reports": sources,
        }
        return payload

    official = reports["official_token"]
    answer_shape = reports["answer_shape"]
    supportable = reports["supportable"]
    endpoint_schema = reports["endpoint_schema"]
    endpoint_tie = reports["endpoint_tie"]
    ast = reports["ast"]
    local_index = reports["local_index"]
    live = reports["live"]
    auto_trial = reports["autonomous"]
    evidence_answer = reports["evidence_answer"]
    llm_answer = reports["llm_answer"]
    hidden = reports["hidden"]

    current_effect = {
        **empty_effect(),
        "strict_score_delta": 0.0,
        "correctness_delta": 0.0,
        "answer_score_delta": current.get("avg_answer_score", UNAVAILABLE),
        "sql_score_delta": current.get("avg_sql_score", UNAVAILABLE),
        "api_score_delta": current.get("avg_api_score", UNAVAILABLE),
        "token_delta": current.get("avg_estimated_tokens", UNAVAILABLE),
        "runtime_delta": current.get("avg_runtime", UNAVAILABLE),
        "tool_call_delta": current.get("avg_tool_call_count", UNAVAILABLE),
    }

    catalog = [
        technique(
            "query_normalizer",
            "Query understanding / routing",
            "Canonicalizes user text before routing and retrieval.",
            "query understanding",
            "raw query",
            "normalized query and rewrite hints",
            "Always runs in packaged path.",
            ["dashagent/query_normalizer.py"],
            ["checkpoint_02_query_normalization"],
            "promoted_default",
            empty_effect(),
            "No hidden-style regression reported.",
            "Deterministic preprocessing; retained as core routing support.",
            [source("outputs/eval/*/sql_first_api_verify/trajectory.json", "checkpoints")],
        ),
        technique(
            "query_tokens",
            "Query understanding / routing",
            "Extracts tokens, quoted entities, and intent words for downstream ranking.",
            "query understanding",
            "normalized query",
            "tokens and quoted entities",
            "Always runs in packaged path.",
            ["dashagent/query_tokens.py"],
            ["checkpoint_03_query_tokens"],
            "promoted_default",
            empty_effect(),
            "No hidden-style regression reported.",
            "Low-cost deterministic signal used by ranking and templates.",
            [source("outputs/eval/*/sql_first_api_verify/trajectory.json", "checkpoints")],
        ),
        technique(
            "relevance_scorer",
            "Query understanding / routing",
            "Ranks schema/API candidates using query-token overlap and metadata relevance.",
            "candidate ranking",
            "tokens, schema metadata, endpoint metadata",
            "candidate relevance scores",
            "Used before metadata selection; no isolated score delta available.",
            ["dashagent/relevance_scorer.py", "dashagent/candidate_ranker.py"],
            ["checkpoint_candidate_context", "checkpoint_06_candidate_ranking"],
            "promoted_default",
            empty_effect(),
            "No hidden-style regression reported.",
            "Core ranking signal; effects are embedded in current packaged metrics.",
            [source("outputs/eval_results_strict.json", "summary.by_strategy.SQL_FIRST_API_VERIFY")],
        ),
        technique(
            "plan_ensemble",
            "Query understanding / routing",
            "Deduplicates and selects a single plan from deterministic planning candidates.",
            "planning",
            "candidate plans",
            "one selected plan",
            "Execute exactly one selected plan per query.",
            ["dashagent/plan_ensemble.py"],
            ["checkpoint_plan_ensemble"],
            "promoted_default",
            empty_effect(),
            "No hidden-style regression reported.",
            "Preserves deterministic single-plan execution.",
            [source("outputs/eval/*/sql_first_api_verify/trajectory.json", "steps")],
        ),
        technique(
            "metadata_selector",
            "Query understanding / routing",
            "Builds compact per-query metadata/context for planning.",
            "context selection",
            "candidate tables, APIs, context cards",
            "metadata.json and filled system prompt context",
            "Always active in packaged SQL_FIRST_API_VERIFY path.",
            ["dashagent/metadata_selector.py"],
            ["checkpoint_metadata_selection"],
            "promoted_default",
            empty_effect(),
            "No hidden-style regression reported.",
            "Needed to keep prompt context compact and deterministic.",
            [source("outputs/eval/*/sql_first_api_verify/metadata.json")],
        ),
        technique(
            "query_analysis",
            "Query understanding / routing",
            "Classifies route type, answer shape, and domain family.",
            "query analysis",
            "query tokens and schema/API hints",
            "route_type, domain_type, answer intent",
            "Always active before planning.",
            ["dashagent/query_analysis.py"],
            ["checkpoint_query_analysis"],
            "promoted_default",
            empty_effect(),
            "Hidden-style 48/48 in current report.",
            "Core deterministic intent layer.",
            [source("outputs/hidden_style_eval.json", "summary")],
        ),
        technique(
            "prompt_router",
            "Query understanding / routing",
            "Fast prompt-level route gate for SQL/API need and risk.",
            "routing",
            "raw query",
            "route policy and requires_api decision",
            "Always runs; conservative API decisions remain guarded.",
            ["dashagent/prompt_router.py", "dashagent/router.py"],
            ["checkpoint_00_prompt_router"],
            "promoted_default",
            empty_effect(),
            "Hidden-style 48/48 in current report.",
            "Promoted as routing safety layer.",
            [source("outputs/eval/*/sql_first_api_verify/trajectory.json", "checkpoint_00_prompt_router")],
        ),
        technique(
            "SQL_FIRST_API_VERIFY",
            "Planning / execution",
            "Grounds with local SQL first, then verifies with API where needed.",
            "strategy",
            "metadata/context and route policy",
            "SQL/API execution plan",
            "Preferred packaged strategy.",
            ["dashagent/executor.py", "dashagent/planner.py"],
            ["checkpoint_planning", "checkpoint_execution"],
            "promoted_default",
            current_effect,
            "Hidden-style 48/48 in current report.",
            "Best current strict score and correctness among packaged strategies.",
            [source("outputs/eval_results_strict.json", "summary.by_strategy.SQL_FIRST_API_VERIFY")],
        ),
        technique(
            "SQL templates",
            "Planning / execution",
            "Generate validated SQL for recurring local-data query families.",
            "SQL planning",
            "schema metadata and query analysis",
            "read-only SQL",
            "Only validated read-only SQL may execute.",
            ["dashagent/sql_templates.py", "dashagent/validators.py"],
            ["checkpoint_sql_template", "checkpoint_sql_ast_validation"],
            "promoted_default",
            empty_effect(),
            "No hidden-style regression reported.",
            "Reusable templates are part of current SQL score.",
            [source("outputs/eval_results_strict.json", "summary.by_strategy.SQL_FIRST_API_VERIFY.avg_sql_score")],
        ),
        technique(
            "API templates",
            "Planning / execution",
            "Generate endpoint-catalog-valid API calls.",
            "API planning",
            "endpoint catalog, route policy, grounded IDs",
            "method/path/params",
            "Catalog validation must pass; dry-run is honest when credentials are absent.",
            ["dashagent/api_templates.py", "dashagent/endpoint_catalog.py"],
            ["checkpoint_api_template", "checkpoint_api_validation"],
            "promoted_default",
            empty_effect(),
            "No hidden-style regression reported.",
            "Reusable endpoint templates drive current API score.",
            [source("outputs/eval_results_strict.json", "summary.by_strategy.SQL_FIRST_API_VERIFY.avg_api_score")],
        ),
        technique(
            "planner",
            "Planning / execution",
            "Builds constrained SQL/API steps from route and context.",
            "planning",
            "route, metadata, templates",
            "candidate plan",
            "Plan optimizer and validators gate execution.",
            ["dashagent/planner.py", "dashagent/executor.py"],
            ["checkpoint_planning"],
            "promoted_default",
            empty_effect(),
            "No hidden-style regression reported.",
            "Core packaged execution path.",
            [source("outputs/eval/*/sql_first_api_verify/trajectory.json", "steps")],
        ),
        technique(
            "executor",
            "Planning / execution",
            "Runs validated SQL/API calls and records trajectory evidence.",
            "execution",
            "selected plan",
            "tool results, evidence, trajectory",
            "Executes one selected plan; no multi-plan runtime execution.",
            ["dashagent/executor.py"],
            ["checkpoint_execution", "checkpoint_answer_synthesis"],
            "promoted_default",
            empty_effect(),
            "No hidden-style regression reported.",
            "Required packaged runtime component.",
            [source("outputs/eval/*/sql_first_api_verify/trajectory.json")],
        ),
        technique(
            "endpoint catalog",
            "Planning / execution",
            "Defines allowed Adobe API endpoints and validation metadata.",
            "API validation",
            "endpoint templates and planned API calls",
            "catalog validation result",
            "Unknown endpoints are rejected.",
            ["dashagent/endpoint_catalog.py"],
            ["checkpoint_api_validation"],
            "promoted_default",
            empty_effect(),
            "No hidden-style regression reported.",
            "Safety boundary for API calls.",
            [source("outputs/eval/*/sql_first_api_verify/trajectory.json", "api validation")],
        ),
        technique(
            "endpoint family ranker",
            "Planning / execution",
            "Ranks endpoint families from reusable intent features.",
            "endpoint ranking",
            "query tokens and endpoint metadata",
            "ranked endpoint families",
            "Packaged ranking signal; v2 tie-break remains shadow-only.",
            ["dashagent/endpoint_family_ranker.py"],
            ["checkpoint_endpoint_family_ranking"],
            "promoted_default",
            empty_effect(),
            "No hidden-style regression reported.",
            "Ranking is used; broader tie-break changes were not promoted.",
            [source("outputs/endpoint_family_tiebreak_v2_shadow.json", "summary")],
        ),
        technique(
            "endpoint-schema rule candidates",
            "Planning / execution",
            "Shadow-tests reusable endpoint/schema routing rules.",
            "endpoint/schema routing",
            "query vocabulary, catalog metadata, path shapes",
            "candidate reranking diagnostics",
            "Canary only; no measurable improvement in current report.",
            ["dashagent/endpoint_schema_rule_candidates.py"],
            ["checkpoint_endpoint_schema_rule_candidates"],
            "shadow_only",
            {
                **empty_effect(),
                "strict_score_delta": endpoint_schema.get("avg_score_delta", UNAVAILABLE),
                "correctness_delta": endpoint_schema.get("avg_correctness_delta", UNAVAILABLE),
                "token_delta": endpoint_schema.get("avg_token_delta", UNAVAILABLE),
                "runtime_delta": endpoint_schema.get("avg_runtime_delta", UNAVAILABLE),
                "tool_call_delta": endpoint_schema.get("avg_tool_delta", UNAVAILABLE),
            },
            "Hidden-style gate passed in canary.",
            "Kept shadow-only because measurable improvement was false.",
            [source("outputs/endpoint_schema_rule_canary.json", "summary")],
        ),
        technique(
            "candidate generation",
            "Planning / execution",
            "Generates deterministic alternative plans for isolated search.",
            "candidate search",
            "query, schema metadata, endpoint catalog",
            "candidate SQL/API/answer plans",
            "Isolated search only; packaged path unchanged.",
            ["dashagent/targeted_candidate_generator.py"],
            ["candidate_search"],
            "shadow_only",
            empty_effect(),
            "No packaged hidden-style effect.",
            "No broad runtime promotion; used for diagnostics/trials.",
            [source("outputs/execution_candidate_search.json", "summary")],
        ),
        technique(
            "execution-based candidate selector",
            "Planning / execution",
            "Scores isolated candidates and selects only safe improvements.",
            "candidate search",
            "candidate plans and strict offline scores",
            "safe candidate bundle",
            "Never changes packaged output directly.",
            ["dashagent/execution_based_candidate_selector.py"],
            ["candidate_search"],
            "shadow_only",
            empty_effect(),
            "No packaged hidden-style effect.",
            "Kept isolated unless trial gates pass.",
            [source("outputs/execution_candidate_search.json", "summary")],
        ),
        technique(
            "answer-shape v2",
            "Planning / execution",
            "Tests concise answer-shape rewrites with row-level A/B diagnostics.",
            "answer synthesis",
            "baseline answer and evidence",
            "candidate answer",
            "Default-off; selected rows only in isolated trial.",
            ["scripts/run_answer_shape_v2_ab_eval.py"],
            ["answer_shape_v2_ab_eval"],
            "default_off",
            {
                **empty_effect(),
                "strict_score_delta": score_delta(answer_shape.get("projected_strict_final_score"), answer_shape.get("baseline_strict_final_score")),
                "correctness_delta": score_delta(answer_shape.get("projected_correctness"), answer_shape.get("baseline_correctness")),
                "answer_score_delta": answer_shape.get("avg_answer_score_delta_changed", UNAVAILABLE),
            },
            "Hidden-style gate passed.",
            "Not a packaged default; isolated trial was below 0.75 target.",
            [source("outputs/answer_shape_v2_ab_eval.json", "summary")],
        ),
        technique(
            "supportable answer rewriter",
            "Planning / execution",
            "Creates evidence-cited dry-run-safe answer rewrites.",
            "answer synthesis",
            "recorded evidence, endpoint params, dry-run labels",
            "supportable answer candidates",
            "Answer-only; SQL/API hashes and tools must stay unchanged.",
            ["dashagent/supportable_answer_rewriter.py"],
            ["supportable_answer_rewrite_eval"],
            "shadow_only",
            {
                **empty_effect(),
                "strict_score_delta": score_delta(supportable.get("best_projected_strict_final_score"), current.get("avg_final_score")),
            },
            "No packaged hidden-style effect.",
            "Safe rows feed isolated trials; not final promoted behavior.",
            [source("outputs/supportable_answer_rewrite_eval.json", "summary")],
        ),
        technique(
            "SQL-only API-skip guard",
            "Planning / execution",
            "Conservatively skips API only when SQL fully answers and API score is not needed.",
            "pre-execution guard",
            "route policy, SQL evidence, strict diagnostics",
            "API_SKIP decision metadata",
            "Default-off.",
            ["dashagent/sql_only_api_skip_guard.py"],
            ["sql_only_api_skip_guard"],
            "default_off",
            empty_effect(),
            "No packaged hidden-style effect.",
            "Not promoted; conservative guard available behind flag only.",
            [source("outputs/live_mode_readiness_report.json", "summary.sql_only_skip_guard_rows")],
        ),
        technique(
            "official-token reduction",
            "Evidence / context / optimization",
            "Reduces context/token cost while preserving packaged behavior.",
            "context optimization",
            "metadata and prompt context",
            "reduced prompt/context tokens",
            "Promoted default and kept enabled.",
            ["dashagent/token_reduction_policy.py", "dashagent/config.py"],
            ["checkpoint_official_token_reduction"],
            "promoted_default",
            {
                **empty_effect(),
                "strict_score_delta": official.get("score_delta", UNAVAILABLE),
                "correctness_delta": score_delta(official.get("promoted_correctness"), official.get("baseline_correctness")),
                "token_delta": official.get("token_delta", UNAVAILABLE),
                "runtime_delta": official.get("runtime_delta", UNAVAILABLE),
                "tool_call_delta": official.get("tool_delta", UNAVAILABLE),
            },
            "Hidden-style remains 48/48.",
            "Promoted because strict score tied/improved safely with large token reduction.",
            [source("outputs/official_token_reduction_promotion_report.json", "summary")],
        ),
        technique(
            "local knowledge index",
            "Evidence / context / optimization",
            "Builds Parquet-derived evidence objects for grounding.",
            "evidence retrieval",
            "DBSnapshot parquet data and schema metadata",
            "provenance-safe evidence objects",
            "Evidence objects only; no final-answer cache.",
            ["dashagent/local_knowledge_index.py"],
            ["local_index_fact_coverage"],
            "diagnostic_only",
            {
                **empty_effect(),
                "strict_score_delta": local_index.get("score_delta_from_local_evidence_total", UNAVAILABLE),
            },
            "No packaged hidden-style effect.",
            "Coverage exists, but score impact is currently 0.",
            [source("outputs/local_index_candidate_eval.json", "summary")],
        ),
        technique(
            "cache",
            "Evidence / context / optimization",
            "Caches deterministic retrieval/index artifacts.",
            "retrieval optimization",
            "schema and value retrieval keys",
            "cache hits or regenerated values",
            "Used only for reproducible local speedups.",
            ["dashagent/cache.py"],
            ["checkpoint_value_entity_retrieval"],
            "promoted_default",
            empty_effect(),
            "No hidden-style regression reported.",
            "Infrastructure; no standalone score claim.",
            [source("outputs/candidate_context_report.json", "rows")],
        ),
        technique(
            "evidence_bus",
            "Evidence / context / optimization",
            "Carries SQL/API/local evidence into answer synthesis.",
            "evidence collection",
            "tool results and local evidence",
            "structured evidence records",
            "Evidence must be recorded before claims can use it.",
            ["dashagent/evidence_bus.py"],
            ["checkpoint_evidence_collection"],
            "promoted_default",
            empty_effect(),
            "No hidden-style regression reported.",
            "Safety layer for supportable answers.",
            [source("outputs/eval/*/sql_first_api_verify/trajectory.json", "steps")],
        ),
        technique(
            "context cards",
            "Evidence / context / optimization",
            "Summarizes schema/API/domain hints for compact prompts.",
            "context selection",
            "schema/API metadata and query analysis",
            "context cards",
            "Packed into prompt metadata.",
            ["dashagent/context_cards.py"],
            ["checkpoint_context_cards"],
            "promoted_default",
            empty_effect(),
            "No hidden-style regression reported.",
            "Core compact context mechanism.",
            [source("outputs/eval/*/sql_first_api_verify/metadata.json")],
        ),
        technique(
            "fast paths",
            "Evidence / context / optimization",
            "Handles simple deterministic query families with low overhead.",
            "planning optimization",
            "query analysis and schema/API hints",
            "fast-path plan or no-op",
            "Validators still gate execution.",
            ["dashagent/fast_paths.py"],
            ["checkpoint_fast_path"],
            "promoted_default",
            empty_effect(),
            "No hidden-style regression reported.",
            "Efficiency-oriented infrastructure.",
            [source("outputs/eval_results_strict.json", "summary")],
        ),
        technique(
            "call budget",
            "Evidence / context / optimization",
            "Limits SQL/API calls for efficiency and trajectory stability.",
            "planning optimization",
            "planned steps and route policy",
            "call budget decision",
            "Prevents uncontrolled tool growth.",
            ["dashagent/call_budget.py"],
            ["checkpoint_11_call_budget"],
            "promoted_default",
            empty_effect(),
            "No hidden-style regression reported.",
            "Keeps tool calls within packaged efficiency target.",
            [source("outputs/eval_results_strict.json", "summary.by_strategy.SQL_FIRST_API_VERIFY.avg_tool_call_count")],
        ),
        technique(
            "evidence policy",
            "Evidence / context / optimization",
            "Decides when SQL/API evidence is sufficient or API is required.",
            "evidence gating",
            "route, SQL results, API policy",
            "evidence sufficiency decision",
            "Must preserve dry-run honesty.",
            ["dashagent/evidence_policy.py"],
            ["checkpoint_evidence_policy"],
            "promoted_default",
            empty_effect(),
            "No hidden-style regression reported.",
            "Promoted core safety/answerability gate.",
            [source("outputs/eval/*/sql_first_api_verify/trajectory.json", "checkpoints")],
        ),
        technique(
            "plan optimizer",
            "Evidence / context / optimization",
            "Deduplicates and budgets plan steps before execution.",
            "planning optimization",
            "planned steps",
            "optimized plan",
            "Preserves one selected execution plan.",
            ["dashagent/plan_optimizer.py"],
            ["checkpoint_plan_optimizer"],
            "promoted_default",
            empty_effect(),
            "No hidden-style regression reported.",
            "Efficiency and safety support for packaged strategy.",
            [source("outputs/eval/*/sql_first_api_verify/trajectory.json", "steps")],
        ),
        technique(
            "compact context experiment",
            "Evidence / context / optimization",
            "Tests smaller context windows under strict gates.",
            "context optimization",
            "candidate context",
            "compact candidate context",
            "Disabled in packaged system.",
            ["dashagent/schema_context_voter.py"],
            ["compact_context_shadow_eval"],
            "default_off",
            empty_effect(),
            "No packaged hidden-style effect; compact context remains disabled.",
            "Not promoted under current safety constraints.",
            [source("outputs/accuracy_promotion_decision_report.json", "compact_context_enabled")],
        ),
        technique(
            "shadow repair",
            "Evidence / context / optimization",
            "Evaluates repaired plans without enabling repair execution.",
            "repair diagnostics",
            "current plan and repaired candidate",
            "shadow repair score comparison",
            "Repair execution remains disabled.",
            ["dashagent/repair_candidate_selector.py", "dashagent/repair_safety_verifier.py"],
            ["shadow_repair_eval"],
            "shadow_only",
            empty_effect(),
            "No packaged hidden-style effect.",
            "Not promoted because repaired candidates did not pass gates.",
            [source("outputs/shadow_repair_eval.json", "summary")],
        ),
        technique(
            "AST-guided SQL candidate canary",
            "Evidence / context / optimization",
            "Tests AST quality as a tie-break for SQL candidates.",
            "SQL candidate diagnostics",
            "candidate SQL",
            "AST validation/ranking diagnostics",
            "Canary only; no applicable rows changed.",
            ["dashagent/sql_ast_candidate_ranker.py"],
            ["ast_guided_sql_candidate_canary"],
            "shadow_only",
            {
                **empty_effect(),
                "strict_score_delta": ast.get("avg_score_delta", UNAVAILABLE),
                "correctness_delta": ast.get("avg_correctness_delta", UNAVAILABLE),
                "token_delta": ast.get("avg_token_delta", UNAVAILABLE),
                "runtime_delta": ast.get("avg_runtime_delta", UNAVAILABLE),
                "tool_call_delta": ast.get("avg_tool_delta", UNAVAILABLE),
            },
            "No hidden-style regression reported.",
            "Kept shadow-only because no alternatives existed.",
            [source("outputs/ast_guided_sql_candidate_canary.json", "summary")],
        ),
        technique(
            "endpoint-family tie-break v2",
            "Evidence / context / optimization",
            "Shadow-tests deterministic preference for high-confidence ranked endpoint family.",
            "endpoint routing diagnostics",
            "ranked and selected endpoint families",
            "divergence report",
            "Shadow-first; no trial-eligible positive rows.",
            ["scripts/run_endpoint_family_tiebreak_v2_shadow.py"],
            ["endpoint_family_tiebreak_v2_shadow"],
            "shadow_only",
            {
                **empty_effect(),
                "strict_score_delta": 0 if endpoint_tie.get("positive_projected_delta_rows") == 0 else UNAVAILABLE,
            },
            "No packaged hidden-style effect.",
            "Kept shadow-only because projected positive delta rows = 0.",
            [source("outputs/endpoint_family_tiebreak_v2_shadow.json", "summary")],
        ),
        technique(
            "live-mode readiness diagnostics",
            "Evidence / context / optimization",
            "Reports whether real Adobe credentials and live API payload readiness exist.",
            "diagnostics",
            "environment credential visibility and trajectories",
            "live readiness report",
            "Diagnostic only unless credentials are present.",
            ["scripts/run_live_mode_readiness_check.py"],
            ["live_mode_readiness_report"],
            "diagnostic_only",
            empty_effect(),
            "Does not change dry-run behavior.",
            "Credential visibility is false, so this remains diagnostic.",
            [source("outputs/live_mode_readiness_report.json", "summary")],
        ),
        technique(
            "hidden-style eval",
            "Safety / robustness / evaluation",
            "Checks paraphrase/hidden-style routing robustness.",
            "evaluation gate",
            "hidden-style cases",
            "pass/fail and stability metrics",
            "Report gate only; runtime behavior unchanged.",
            ["scripts/run_hidden_style_eval.py"],
            ["hidden_style_eval"],
            "diagnostic_only",
            empty_effect(),
            f"Passed {get_path(load_json('outputs/hidden_style_eval.json'), 'summary', 'passed_cases')}/"
            f"{get_path(load_json('outputs/hidden_style_eval.json'), 'summary', 'total_cases')}; "
            f"family stability {get_path(load_json('outputs/hidden_style_eval.json'), 'summary', 'family_stability_rate')}; "
            f"schema stability {get_path(load_json('outputs/hidden_style_eval.json'), 'summary', 'schema_stability_rate')}.",
            "Prevents weakening schema/family routing robustness; current report passes 48/48.",
            [source("outputs/hidden_style_eval.json", "summary")],
        ),
        technique(
            "leakage / robustness checks",
            "Safety / robustness / evaluation",
            "Rejects query-id, exact-query, gold-path, or answer-memorization behavior.",
            "safety gate",
            "candidate triggers and reports",
            "leakage pass/fail flags",
            "Applied to canaries/trials.",
            ["tests/test_score075_robustness_leakage.py"],
            ["leakage_check"],
            "diagnostic_only",
            empty_effect(),
            "No leakage flags in current canary summaries.",
            "Required gate for all accuracy experiments.",
            [source("outputs/endpoint_schema_rule_canary.json", "summary.leakage_check_passed")],
        ),
        technique(
            "answer verifier",
            "Safety / robustness / evaluation",
            "Checks final answer support and consistency.",
            "answer validation",
            "final answer and evidence",
            "verification result",
            "Runs before final answer logging.",
            ["dashagent/answer_verifier.py"],
            ["checkpoint_16_answer_verification"],
            "promoted_default",
            empty_effect(),
            "No hidden-style regression reported.",
            "Core answer safety check.",
            [source("outputs/eval/*/sql_first_api_verify/trajectory.json", "checkpoint_16_answer_verification")],
        ),
        technique(
            "answer reranker",
            "Safety / robustness / evaluation",
            "Ranks candidate answer phrasings when alternatives are available.",
            "answer synthesis",
            "candidate answers",
            "selected answer",
            "Must stay evidence-supported.",
            ["dashagent/answer_reranker.py"],
            ["answer_reranker"],
            "promoted_default",
            empty_effect(),
            "No hidden-style regression reported.",
            "Used as packaged answer-selection support.",
            [source("outputs/eval/*/sql_first_api_verify/trajectory.json", "answer checkpoints")],
        ),
        technique(
            "answer claims / slots / intent / diagnostics",
            "Safety / robustness / evaluation",
            "Extracts answer shape, requested facts, and diagnostic slots.",
            "answer analysis",
            "query and answer evidence",
            "answer intent/slots/claims",
            "No unsupported claim should become a final fact.",
            ["dashagent/answer_claims.py", "dashagent/answer_slots.py", "dashagent/answer_intent.py", "dashagent/answer_diagnostics.py"],
            ["answer_diagnostics"],
            "promoted_default",
            empty_effect(),
            "No hidden-style regression reported.",
            "Supports evidence-bound answer generation.",
            [source("outputs/score_component_error_report.json", "summary")],
        ),
        technique(
            "package readiness checks",
            "Safety / robustness / evaluation",
            "Verifies packaged outputs and final submission readiness.",
            "packaging gate",
            "final submission artifacts",
            "readiness result",
            "Does not change runtime behavior.",
            ["scripts/check_submission_ready.py"],
            ["check_submission_ready"],
            "diagnostic_only",
            empty_effect(),
            "No hidden-style effect.",
            "Final readiness gate remains passing in winner report.",
            [source("outputs/winner_readiness_report.json", "final_recommendation")],
        ),
        technique(
            "secret scan",
            "Safety / robustness / evaluation",
            "Prevents credential leakage in packaged outputs/reports.",
            "packaging gate",
            "repo outputs and final submission",
            "no_secret_scan result",
            "Does not change runtime behavior.",
            ["scripts/check_submission_ready.py"],
            ["no_secret_scan"],
            "diagnostic_only",
            empty_effect(),
            "No hidden-style effect.",
            "Required readiness gate.",
            [source("outputs/winner_readiness_report.json", "packaged")],
        ),
        technique(
            "trajectory checkpoints",
            "Safety / robustness / evaluation",
            "Records execution checkpoints for explainability and auditability.",
            "observability",
            "pipeline stage outputs",
            "trajectory checkpoint list",
            "Always written for packaged query outputs.",
            ["dashagent/trajectory.py", "dashagent/span_exporter.py"],
            ["checkpoints"],
            "promoted_default",
            empty_effect(),
            "No hidden-style regression reported.",
            "Core observability surface used by these visualizations.",
            [source("outputs/eval/*/sql_first_api_verify/trajectory.json", "checkpoints")],
        ),
        technique(
            "OpenRouter LLM rewrite search",
            "Safety / robustness / evaluation",
            "Uses LLM proposals only for evidence-cited answer rewrites.",
            "isolated candidate search",
            "baseline answer and local evidence registry",
            "candidate rewrites with claim citations",
            "LLM output is proposal-only and must pass local validators.",
            ["dashagent/llm_candidate_generator.py", "scripts/run_llm_answer_rewrite_search.py"],
            ["llm_answer_rewrite_search"],
            "shadow_only",
            empty_effect(),
            "No packaged hidden-style effect.",
            f"Kept shadow-only; safe rows = {llm_answer.get('safe_rows', UNAVAILABLE)}.",
            [source("outputs/llm_answer_rewrite_search.json", "summary")],
        ),
        technique(
            "supportable dry-run rewrite validation",
            "Safety / robustness / evaluation",
            "Validates claim citations, dry-run unavailable wording, and SQL/API hash invariance.",
            "answer candidate safety",
            "candidate rewrites",
            "safe/unsafe rewrite labels",
            "Rejects fabricated payloads and unsupported claims.",
            ["dashagent/supportable_answer_rewriter.py"],
            ["supportable_answer_rewrite_eval"],
            "shadow_only",
            {
                **empty_effect(),
                "strict_score_delta": score_delta(evidence_answer.get("best_projected_strict_final_score"), current.get("avg_final_score")),
            },
            "No packaged hidden-style effect.",
            "Safe rows feed isolated trials only.",
            [source("outputs/evidence_answer_candidate_eval.json", "summary")],
        ),
        technique(
            "autonomous packaged trials",
            "Safety / robustness / evaluation",
            "Runs isolated packaged-style trials over safe candidate bundles.",
            "isolated trial",
            "safe candidate bundle",
            "best isolated score and gate results",
            "Does not overwrite official packaged outputs.",
            ["scripts/run_autonomous_packaged_trial.py"],
            ["autonomous_packaged_trial"],
            "shadow_only",
            {
                **empty_effect(),
                "strict_score_delta": auto_trial.get("score_delta", UNAVAILABLE),
                "correctness_delta": auto_trial.get("correctness_delta", UNAVAILABLE),
                "token_delta": auto_trial.get("token_delta", UNAVAILABLE),
                "runtime_delta": auto_trial.get("runtime_delta", UNAVAILABLE),
                "tool_call_delta": auto_trial.get("tool_delta", UNAVAILABLE),
            },
            "Hidden-style gate passed in trial summary.",
            "Best isolated score improved but target 0.75 was not reached.",
            [source("outputs/autonomous_packaged_trial.json", "summary")],
        ),
    ]
    return catalog


def load_reports() -> dict[str, dict[str, Any]]:
    return {
        "official_token": load_json("outputs/official_token_reduction_promotion_report.json", {}),
        "answer_shape": load_json("outputs/answer_shape_v2_ab_eval.json", {}).get("summary", {}),
        "supportable": load_json("outputs/supportable_answer_rewrite_eval.json", {}).get("summary", {}),
        "endpoint_schema": load_json("outputs/endpoint_schema_rule_canary.json", {}).get("summary", {}),
        "endpoint_tie": load_json("outputs/endpoint_family_tiebreak_v2_shadow.json", {}).get("summary", {}),
        "ast": load_json("outputs/ast_guided_sql_candidate_canary.json", {}).get("summary", {}),
        "local_index": load_json("outputs/local_index_candidate_eval.json", {}).get("summary", {}),
        "live": load_json("outputs/live_mode_readiness_report.json", {}).get("summary", {}),
        "autonomous": load_json("outputs/autonomous_packaged_trial.json", {}).get("summary", {}),
        "evidence_answer": load_json("outputs/evidence_answer_candidate_eval.json", {}).get("summary", {}),
        "llm_answer": load_json("outputs/llm_answer_rewrite_search.json", {}).get("summary", {}),
        "hidden": load_json("outputs/hidden_style_eval.json", {}).get("summary", {}),
    }


def build_markdown(catalog: list[dict[str, Any]]) -> str:
    lines = ["# DASHSys Technique Catalog", ""]
    lines.append("Every technique below is tied to source artifacts. Missing measurements are marked `unavailable` rather than inferred.")
    lines.append("")
    rows = []
    for item in catalog:
        effect = item["measured_effect"]
        rows.append(
            [
                item["technique_name"],
                item["category"],
                item["stage_in_pipeline"],
                item["default_state"],
                effect.get("strict_score_delta", UNAVAILABLE),
                effect.get("correctness_delta", UNAVAILABLE),
                effect.get("token_delta", UNAVAILABLE),
                item["why_promoted_or_not"],
            ]
        )
    lines.append(table(["Technique", "Category", "Stage", "State", "Strict Δ", "Correctness Δ", "Token Δ", "Rationale"], rows))
    lines.append("")
    for category in sorted({item["category"] for item in catalog}):
        lines.append(f"## {category}")
        for item in [entry for entry in catalog if entry["category"] == category]:
            effect = item["measured_effect"]
            lines.extend(
                [
                    f"### {item['technique_name']}",
                    "",
                    table(
                        ["Field", "Value"],
                        [
                            ["Purpose", item["purpose"]],
                            ["Pipeline stage", item["stage_in_pipeline"]],
                            ["Input", item["input_data"]],
                            ["Output", item["output_data"]],
                            ["Decision boundary", item["decision_boundary"]],
                            ["State", item["default_state"]],
                            ["Files/modules", ", ".join(item["files_modules_involved"])],
                            ["Checkpoints", ", ".join(item["checkpoint_names_involved"])],
                            ["Strict Δ", effect.get("strict_score_delta", UNAVAILABLE)],
                            ["Correctness Δ", effect.get("correctness_delta", UNAVAILABLE)],
                            ["Answer Δ", effect.get("answer_score_delta", UNAVAILABLE)],
                            ["SQL Δ", effect.get("sql_score_delta", UNAVAILABLE)],
                            ["API Δ", effect.get("api_score_delta", UNAVAILABLE)],
                            ["Token Δ", effect.get("token_delta", UNAVAILABLE)],
                            ["Runtime Δ", effect.get("runtime_delta", UNAVAILABLE)],
                            ["Tool Δ", effect.get("tool_call_delta", UNAVAILABLE)],
                            ["Hidden-style impact", item["hidden_style_impact"]],
                            ["Safety notes", item["safety_notes"]],
                            ["Why promoted / not promoted", item["why_promoted_or_not"]],
                            ["Source reports", ", ".join(src["path"] + (f"#{src['field']}" if "field" in src else "") for src in item["source_reports"])],
                        ],
                    ),
                    "",
                ]
            )
    return "\n".join(lines)


if __name__ == "__main__":
    raise SystemExit(main())
